# OKD Agent-based Installation Inventory
# =============================================================================

[local]
localhost ansible_connection=local

[local:vars]
ansible_python_interpreter=/usr/bin/python3

[pfsense]
pfsense-gw ansible_host=192.168.0.101

[pfsense:vars]
ansible_user=admin
ansible_password=unix
ansible_become=no
ansible_python_interpreter=/usr/local/bin/python3.11
ansible_shell_type=csh
